name: pipeline de déploiement de la websms sur un serveur distant

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    
  deploiement:
    runs-on: self-hosted
    steps:
    - uses:  actions/checkout@v5.0.0
    
    - name: Connection a DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
     
    - name: Exécution
      run : |
       ssh rocky@192.168.1.67 "
        git clone https://github.com/naomieassi-arolitec/websms.git
        docker compose pull 
        docker compose down
        docker compose up -d"
