name: pipeline de déploiement de la websms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
    
  deploiement:
    runs-on: self-hosted
    steps:
    - uses:  actions/checkout@v5.0.0
    
    - name: Connection a DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Exécution
      run : |
        cd websms
        docker compose down
        docker compose up compose.yml -d
