name: pipeline de déploiement de la websms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
    
  deploiement:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4

    - name: cloner le repo github
      run: |
        git clone https://github.com/naomieassi-arolitec/websms
        cd websms-js-deployment
    
    - name: Connection a DockerHub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Exécution
      run : |
        docker compose down
        docker compose up compose.yml up -d
